/* XPM */
static const char * blue_xpm[] = {
"16 16 5 1",
"  c black",
". c navy",
"X c blue",
"o c cyan",
"O c None",
"OOOOOOOOOOOOOOOO",
"OOOOOOO.OOOOOOOO",
"OOOOOO.X OOOOOOO",
"OOOOO.oXX OOOOOO",
"OOOO.ooXXX OOOOO",
"OOO.oooXXXX OOOO",
"OO.ooooXXXXX OOO",
"O.XXXXX...... OO",
"OO.XXXX..... OOO",
"OOO.XXX.... OOOO",
"OOOO.XX... OOOOO",
"OOOOO.X.. OOOOOO",
"OOOOOO.. OOOOOOO",
"OOOOOOO OOOOOOOO",
"OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO"
};
